#!/usr/bin/env bash

file="$HOME/.config/kaomoji_list"

category="$(grep -oi "[^ ]\+$" $file | uniq)"
cat="$(echo "$category" | dmenu -l 6 -b -i)"

kaomoji="$(grep $cat $file |sed "s/ $cat//g" | dmenu -l 6 -b -i)"

echo $kaomoji | xclip -selection clipboard
